/**
 * BillboardFigure — Photorealistic character billboard sprites for arch-viz.
 *
 * Uses a chroma-key shader to remove green-screen backgrounds generated by
 * the AI model, with green spill suppression on hair/clothing edges.
 */
import { useRef, useMemo } from 'react';
import * as THREE from 'three';
import { useFrame, useThree, extend } from '@react-three/fiber';
import { useTexture, shaderMaterial } from '@react-three/drei';

// ── Pre-baked sprite descriptors ──────────────────────────
export interface CharacterSprite {
  id: string;
  label: string;
  promptHint: string;
  aspect: number;
  url?: string;
}

export const CHARACTER_CATALOG: CharacterSprite[] = [
  { id: 'visitor-m1', label: 'Male Visitor 1', promptHint: 'professional man in business casual, navy blazer, standing relaxed at trade show, full body, front view', aspect: 0.45 },
  { id: 'visitor-f1', label: 'Female Visitor 1', promptHint: 'professional woman in business attire, holding coffee, standing at convention, full body, front view', aspect: 0.42 },
  { id: 'visitor-m2', label: 'Male Visitor 2', promptHint: 'young man in polo shirt with conference lanyard, looking at booth, full body, slight angle', aspect: 0.44 },
  { id: 'visitor-f2', label: 'Female Visitor 2', promptHint: 'woman in smart casual blazer, holding tablet, at trade show, full body, front view', aspect: 0.43 },
  { id: 'visitor-m3', label: 'Male Visitor 3', promptHint: 'middle-aged man in suit, hands in pockets, at expo hall, full body, front view', aspect: 0.46 },
  { id: 'visitor-f3', label: 'Female Visitor 3', promptHint: 'young professional woman with backpack, at convention center, full body, walking pose', aspect: 0.42 },
  { id: 'staff-m1', label: 'Male Staff 1', promptHint: 'friendly male booth staff in branded polo shirt, arms crossed, professional pose, full body, front view', aspect: 0.45 },
  { id: 'staff-f1', label: 'Female Staff 1', promptHint: 'friendly female booth representative in branded polo, welcoming gesture, full body, front view', aspect: 0.42 },
  { id: 'phone-m1', label: 'Man on Phone', promptHint: 'business man looking at smartphone, conference lanyard, standing, full body, front view', aspect: 0.43 },
  { id: 'photo-f1', label: 'Woman Taking Photo', promptHint: 'woman taking photo with phone at trade show booth, full body, slight angle', aspect: 0.44 },
  { id: 'group-pair', label: 'Conversation Pair', promptHint: 'two professionals talking to each other at trade show, conference badges, full body, side view', aspect: 0.8 },
  { id: 'visitor-m4', label: 'Male Visitor 4', promptHint: 'casual tech professional in t-shirt and jeans, conference badge, standing relaxed, full body, front view', aspect: 0.44 },
];

export function getCharacterBySeed(seed: number, isStaff = false): CharacterSprite {
  const pool = isStaff
    ? CHARACTER_CATALOG.filter(c => c.id.startsWith('staff-'))
    : CHARACTER_CATALOG.filter(c => !c.id.startsWith('staff-') && c.id !== 'group-pair');
  return pool[Math.abs(seed) % pool.length];
}

// ── Chroma-key green-screen removal shader ──────────────
const CutoutMaterial = shaderMaterial(
  {
    map: null as THREE.Texture | null,
    keyColor: new THREE.Color(0, 1, 0), // #00FF00 green screen
    similarity: 0.35,   // how close to key color triggers removal
    smoothness: 0.12,   // edge softness
    spillReduction: 0.7, // green spill removal from edges
    whiteThreshold: 0.95, // remove near-white backgrounds too
    whiteSmoothness: 0.03,
    whiteDespill: 0.25,
  },
  // Vertex
  `
    varying vec2 vUv;
    void main() {
      vUv = uv;
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
    }
  `,
  // Fragment — chroma-key with white-background fallback + spill suppression
  `
    uniform sampler2D map;
    uniform vec3 keyColor;
    uniform float similarity;
    uniform float smoothness;
    uniform float spillReduction;
    uniform float whiteThreshold;
    uniform float whiteSmoothness;
    uniform float whiteDespill;
    varying vec2 vUv;
    
    // Convert RGB to YCbCr for perceptual chroma keying
    vec2 rgbToChroma(vec3 rgb) {
      float Y = 0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b;
      float Cb = 0.5 - 0.168736 * rgb.r - 0.331264 * rgb.g + 0.5 * rgb.b;
      float Cr = 0.5 + 0.5 * rgb.r - 0.418688 * rgb.g - 0.081312 * rgb.b;
      return vec2(Cb, Cr);
    }

    void main() {
      vec4 texColor = texture2D(map, vUv);
      if (texColor.a <= 0.001) discard;

      vec3 rgb = texColor.rgb;
      
      // --- Method 1: Chroma distance in YCbCr space (green screen) ---
      vec2 chromaSample = rgbToChroma(rgb);
      vec2 chromaKey = rgbToChroma(keyColor);
      float chromaDist = distance(chromaSample, chromaKey);
      float chromaMask = smoothstep(similarity, similarity + smoothness, chromaDist);
      
      // --- Method 2: Direct green dominance check ---
      float greenDominance = rgb.g - max(rgb.r, rgb.b);
      float greenMask = 1.0 - smoothstep(0.08, 0.28, greenDominance);
      
      // --- Method 3: Pure color distance fallback ---
      float colorDist = distance(rgb, keyColor);
      float colorMask = smoothstep(0.35, 0.55, colorDist);

      float greenAlpha = min(chromaMask, min(greenMask, colorMask));

      // --- Method 4: white backdrop removal fallback ---
      float maxCh = max(rgb.r, max(rgb.g, rgb.b));
      float minCh = min(rgb.r, min(rgb.g, rgb.b));
      float sat = maxCh - minCh;
      float nearWhite = smoothstep(whiteThreshold - whiteSmoothness, whiteThreshold + whiteSmoothness, minCh);
      float lowSaturation = 1.0 - smoothstep(0.03, 0.18, sat);
      float whiteMask = 1.0 - (nearWhite * lowSaturation);
      
      float alpha = texColor.a * min(greenAlpha, whiteMask);
      
      // Hard discard for pure backdrop pixels (green OR white)
      if (greenDominance > 0.15 && chromaDist < similarity * 1.8) discard;
      if (minCh > 0.97 && sat < 0.04) discard;
      if (alpha < 0.05) discard;
      
      // --- Spill suppression on edge pixels ---
      float spillAmount = max(0.0, rgb.g - mix(rgb.r, rgb.b, 0.5)) * (1.0 - alpha * 0.5);
      vec3 despilled = rgb;
      despilled.g -= spillAmount * spillReduction;

      // Minimal white fringe neutralization — avoid over-darkening edges
      float whiteFringe = smoothstep(0.92, 1.0, minCh) * lowSaturation * (1.0 - alpha);
      float luma = dot(despilled, vec3(0.299, 0.587, 0.114));
      despilled = mix(despilled, vec3(luma), whiteFringe * whiteDespill);
      despilled = clamp(despilled, 0.0, 1.0);
      
      gl_FragColor = vec4(despilled, alpha);
    }
  `
);

extend({ CutoutMaterial });

declare global {
  namespace JSX {
    interface IntrinsicElements {
      cutoutMaterial: any;
    }
  }
}

// ── Billboard Figure Component ────────────────────────────

interface BillboardFigureProps {
  position: [number, number, number];
  rotation?: number;
  opacity?: number;
  spriteUrl: string;
  height?: number;
  aspect?: number;
}

export function BillboardFigure({
  position,
  rotation = 0,
  opacity = 1,
  spriteUrl,
  height = 1.75,
  aspect: fallbackAspect = 0.45,
}: BillboardFigureProps) {
  const meshRef = useRef<THREE.Mesh>(null);
  const { camera } = useThree();

  const texture = useTexture(spriteUrl);

  useMemo(() => {
    texture.colorSpace = THREE.SRGBColorSpace;
    texture.minFilter = THREE.LinearFilter;
    texture.magFilter = THREE.LinearFilter;
    texture.wrapS = THREE.ClampToEdgeWrapping;
    texture.wrapT = THREE.ClampToEdgeWrapping;
    texture.premultiplyAlpha = false; // Must be false for chroma-key
    texture.anisotropy = 16;
  }, [texture]);

  // Derive aspect from actual texture dimensions for proper proportions
  const aspect = useMemo(() => {
    const img = texture.image as HTMLImageElement | undefined;
    if (img && img.width && img.height) {
      return img.width / img.height;
    }
    return fallbackAspect;
  }, [texture, fallbackAspect]);

  const width = height * aspect;

  useFrame(() => {
    if (meshRef.current) {
      const cameraWorldPos = new THREE.Vector3();
      camera.getWorldPosition(cameraWorldPos);
      const meshWorldPos = new THREE.Vector3();
      meshRef.current.getWorldPosition(meshWorldPos);
      const dx = cameraWorldPos.x - meshWorldPos.x;
      const dz = cameraWorldPos.z - meshWorldPos.z;
      meshRef.current.rotation.y = Math.atan2(dx, dz);
    }
  });

  return (
    <group>
      <mesh
        ref={meshRef}
        position={[position[0], position[1] + height / 2, position[2]]}
      >
        <planeGeometry args={[width, height]} />
        <cutoutMaterial
          map={texture}
          keyColor={[0, 1, 0]}
          similarity={0.35}
          smoothness={0.12}
          spillReduction={0.7}
          whiteThreshold={0.95}
          whiteSmoothness={0.03}
          whiteDespill={0.25}
          transparent={true}
          side={THREE.DoubleSide}
          depthWrite={false}
        />
      </mesh>
      {/* Realistic elliptical contact shadow on the ground */}
      <mesh
        position={[position[0], position[1] + 0.005, position[2]]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <circleGeometry args={[width * 0.55, 32]} />
        <meshBasicMaterial
          color="#000000"
          transparent
          opacity={0.18}
          depthWrite={false}
        />
      </mesh>
    </group>
  );
}

/** Conversation group using billboard sprites */
export function BillboardConversationGroup({
  position,
  spriteUrls,
  count = 2,
}: {
  position: [number, number, number];
  spriteUrls: string[];
  count?: number;
}) {
  const angles = count === 2 ? [0, Math.PI] : [0, Math.PI * 0.7, Math.PI * 1.3];
  const radius = 0.55;

  return (
    <group position={position}>
      {angles.map((angle, i) => {
        const url = spriteUrls[i % spriteUrls.length];
        if (!url) return null;
        return (
          <BillboardFigure
            key={i}
            position={[Math.sin(angle) * radius, 0, Math.cos(angle) * radius]}
            rotation={angle + Math.PI}
            opacity={1}
            spriteUrl={url}
            height={1.65 + (i * 7 % 5) * 0.03}
          />
        );
      })}
    </group>
  );
}
