import { SignatureStyle } from '@/types/brand';
import { DEFAULT_DARK, DEFAULT_ACCENT, DEFAULT_CONFIDENTIALITY } from './signatureConstants';

export interface SignatureTemplate {
  id: string;
  name: string;
  category: 'transperfect' | 'professional' | 'modern' | 'creative' | 'minimal' | 'corporate';
  description: string;
  variant: 'full' | 'reply' | 'minimal';
  style: SignatureStyle;
  includeConfidentiality?: boolean;
  includeSocialPlaceholders?: boolean;
  /** Accent swatch shown on template card */
  accentSwatch?: string;
}

export const SIGNATURE_TEMPLATES: SignatureTemplate[] = [
  // ═══════════════════════════════
  // ── TRANSPERFECT DEFAULT (1) ──
  // ═══════════════════════════════
  {
    id: 'tp-default',
    name: 'TransPerfect Default',
    category: 'transperfect',
    description: 'Official TransPerfect internal signature: logo, vertical bar, contact details with P/M/LinkedIn',
    variant: 'full',
    accentSwatch: DEFAULT_DARK,
    style: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 13,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_DARK,
      textColor: '#222222',
      linkColor: DEFAULT_DARK,
      dividerStyle: 'solid',
      dividerColor: '#cccccc',
      dividerWidth: 1,
      spacing: 14,
      layout: 'horizontal',
      layoutTemplate: 'tp-default',
    },
    includeConfidentiality: true,
    includeSocialPlaceholders: true,
  },

  // ═══════════════════════════════
  // ── PROFESSIONAL (5) ──
  // ═══════════════════════════════
  {
    id: 'pro-classic',
    name: 'Classic Professional',
    category: 'professional',
    description: 'Traditional logo-left layout with clean divider',
    variant: 'full',
    accentSwatch: DEFAULT_ACCENT,
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 18,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#666666',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'solid',
      dividerColor: DEFAULT_ACCENT,
      dividerWidth: 2,
      spacing: 15,
      layout: 'horizontal',
      layoutTemplate: 'classic',
    },
    includeConfidentiality: true,
  },
  {
    id: 'pro-executive',
    name: 'Executive Gold',
    category: 'professional',
    description: 'Two-column split layout with serif typography for C-suite',
    variant: 'full',
    accentSwatch: '#8B6914',
    style: {
      fontFamily: 'Georgia, serif',
      nameFontSize: 20,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1a1a1a',
      titleColor: '#8B6914',
      textColor: '#555555',
      linkColor: '#8B6914',
      dividerStyle: 'double',
      dividerColor: '#8B6914',
      dividerWidth: 3,
      spacing: 18,
      layout: 'horizontal',
      layoutTemplate: 'two-column',
    },
    includeConfidentiality: true,
  },
  {
    id: 'pro-consultant',
    name: 'Consultant Blue',
    category: 'professional',
    description: 'Banner-top accent bar for consulting & advisory',
    variant: 'full',
    accentSwatch: '#3498DB',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#2C3E50',
      titleColor: '#3498DB',
      textColor: '#7F8C8D',
      linkColor: '#3498DB',
      dividerStyle: 'solid',
      dividerColor: '#3498DB',
      dividerWidth: 1,
      spacing: 14,
      layout: 'horizontal',
      layoutTemplate: 'banner-top',
    },
    includeConfidentiality: false,
  },
  {
    id: 'pro-attorney',
    name: 'Legal Authority',
    category: 'professional',
    description: 'Side-banner formal serif for law firms',
    variant: 'full',
    accentSwatch: '#1C3A5F',
    style: {
      fontFamily: "'Times New Roman', serif",
      nameFontSize: 19,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1C3A5F',
      titleColor: '#4A6FA5',
      textColor: '#555555',
      linkColor: '#4A6FA5',
      dividerStyle: 'double',
      dividerColor: '#1C3A5F',
      dividerWidth: 2,
      spacing: 16,
      layout: 'horizontal',
      layoutTemplate: 'side-banner',
    },
    includeConfidentiality: true,
  },
  {
    id: 'pro-healthcare',
    name: 'Medical Professional',
    category: 'professional',
    description: 'Centered layout with teal theme for healthcare',
    variant: 'full',
    accentSwatch: '#0D9488',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#134E4A',
      titleColor: '#0D9488',
      textColor: '#64748B',
      linkColor: '#0D9488',
      dividerStyle: 'solid',
      dividerColor: '#0D9488',
      dividerWidth: 2,
      spacing: 14,
      layout: 'horizontal',
      layoutTemplate: 'centered',
    },
    includeConfidentiality: true,
    includeSocialPlaceholders: true,
  },

  // ═══════════════════════════════
  // ── MODERN (5) ──
  // ═══════════════════════════════
  {
    id: 'mod-clean',
    name: 'Modern Clean',
    category: 'modern',
    description: 'Card-style with accent header for creative agencies',
    variant: 'full',
    accentSwatch: '#FF6B35',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 16,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#111111',
      titleColor: '#FF6B35',
      textColor: '#888888',
      linkColor: '#FF6B35',
      dividerStyle: 'solid',
      dividerColor: '#FF6B35',
      dividerWidth: 3,
      spacing: 12,
      layout: 'horizontal',
      layoutTemplate: 'card',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'mod-gradient',
    name: 'Purple Haze',
    category: 'modern',
    description: 'Stacked vertical layout with purple accents',
    variant: 'full',
    accentSwatch: '#6C3483',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#6C3483',
      titleColor: '#2980B9',
      textColor: '#666666',
      linkColor: '#2980B9',
      dividerStyle: 'solid',
      dividerColor: '#6C3483',
      dividerWidth: 3,
      spacing: 15,
      layout: 'horizontal',
      layoutTemplate: 'stacked',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'mod-tech',
    name: 'Dev Stack',
    category: 'modern',
    description: 'Side-banner dark theme for engineers & tech teams',
    variant: 'full',
    accentSwatch: '#58A6FF',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 16,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#0D1117',
      titleColor: '#58A6FF',
      textColor: '#8B949E',
      linkColor: '#58A6FF',
      dividerStyle: 'dashed',
      dividerColor: '#30363D',
      dividerWidth: 1,
      spacing: 12,
      layout: 'horizontal',
      layoutTemplate: 'side-banner',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'mod-rose',
    name: 'Rosé Minimal',
    category: 'modern',
    description: 'Centered layout with soft rose for beauty & lifestyle',
    variant: 'full',
    accentSwatch: '#E11D48',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 17,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#1F2937',
      titleColor: '#E11D48',
      textColor: '#9CA3AF',
      linkColor: '#E11D48',
      dividerStyle: 'solid',
      dividerColor: '#FECDD3',
      dividerWidth: 2,
      spacing: 14,
      layout: 'vertical',
      layoutTemplate: 'centered',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'mod-midnight',
    name: 'Midnight Indigo',
    category: 'modern',
    description: 'Banner-top with electric blue for fintech & SaaS',
    variant: 'full',
    accentSwatch: '#4F46E5',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#1E1B4B',
      titleColor: '#4F46E5',
      textColor: '#6B7280',
      linkColor: '#4F46E5',
      dividerStyle: 'solid',
      dividerColor: '#4F46E5',
      dividerWidth: 2,
      spacing: 15,
      layout: 'horizontal',
      layoutTemplate: 'banner-top',
    },
    includeSocialPlaceholders: true,
  },

  // ═══════════════════════════════
  // ── CREATIVE (5) ──
  // ═══════════════════════════════
  {
    id: 'cre-bold',
    name: 'Bold Impact',
    category: 'creative',
    description: 'Card layout with red accent header for max visibility',
    variant: 'full',
    accentSwatch: '#E74C3C',
    style: {
      fontFamily: 'Verdana, sans-serif',
      nameFontSize: 20,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: '#E74C3C',
      titleColor: '#2C3E50',
      textColor: '#555555',
      linkColor: '#E74C3C',
      dividerStyle: 'solid',
      dividerColor: '#E74C3C',
      dividerWidth: 4,
      spacing: 16,
      layout: 'horizontal',
      layoutTemplate: 'card',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'cre-artistic',
    name: 'Forest Studio',
    category: 'creative',
    description: 'Stacked organic greens with serif for artisans',
    variant: 'full',
    accentSwatch: '#40916C',
    style: {
      fontFamily: 'Georgia, serif',
      nameFontSize: 19,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1B4332',
      titleColor: '#40916C',
      textColor: '#6B705C',
      linkColor: '#40916C',
      dividerStyle: 'dotted',
      dividerColor: '#40916C',
      dividerWidth: 2,
      spacing: 16,
      layout: 'vertical',
      layoutTemplate: 'stacked',
    },
  },
  {
    id: 'cre-neon',
    name: 'Neon Pop',
    category: 'creative',
    description: 'Side-banner magenta and purple for entertainment',
    variant: 'full',
    accentSwatch: '#F72585',
    style: {
      fontFamily: 'Tahoma, sans-serif',
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#7209B7',
      titleColor: '#F72585',
      textColor: '#555555',
      linkColor: '#F72585',
      dividerStyle: 'solid',
      dividerColor: '#7209B7',
      dividerWidth: 3,
      spacing: 14,
      layout: 'horizontal',
      layoutTemplate: 'side-banner',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'cre-sunset',
    name: 'Sunset Glow',
    category: 'creative',
    description: 'Two-column warm amber for hospitality & travel',
    variant: 'full',
    accentSwatch: '#F59E0B',
    style: {
      fontFamily: 'Verdana, sans-serif',
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#78350F',
      titleColor: '#D97706',
      textColor: '#92400E',
      linkColor: '#D97706',
      dividerStyle: 'solid',
      dividerColor: '#F59E0B',
      dividerWidth: 3,
      spacing: 15,
      layout: 'horizontal',
      layoutTemplate: 'two-column',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'cre-ocean',
    name: 'Ocean Breeze',
    category: 'creative',
    description: 'Centered cyan for marine, wellness & spa',
    variant: 'full',
    accentSwatch: '#06B6D4',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#164E63',
      titleColor: '#06B6D4',
      textColor: '#6B7280',
      linkColor: '#06B6D4',
      dividerStyle: 'solid',
      dividerColor: '#06B6D4',
      dividerWidth: 2,
      spacing: 14,
      layout: 'vertical',
      layoutTemplate: 'centered',
    },
  },

  // ═══════════════════════════════
  // ── MINIMAL (5) ──
  // ═══════════════════════════════
  {
    id: 'min-simple',
    name: 'Pure Text',
    category: 'minimal',
    description: 'Inline single-line with zero graphics',
    variant: 'minimal',
    accentSwatch: '#333333',
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 14,
      titleFontSize: 12,
      textFontSize: 12,
      nameColor: '#333333',
      titleColor: '#666666',
      textColor: '#999999',
      linkColor: '#666666',
      dividerStyle: 'none',
      spacing: 8,
      layoutTemplate: 'inline',
    },
  },
  {
    id: 'min-reply',
    name: 'Quick Reply',
    category: 'minimal',
    description: 'Ultra-condensed for email thread replies',
    variant: 'reply',
    accentSwatch: DEFAULT_ACCENT,
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 14,
      titleFontSize: 12,
      textFontSize: 12,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#666666',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'none',
      spacing: 10,
      layoutTemplate: 'classic',
    },
  },
  {
    id: 'min-oneline',
    name: 'One-Liner',
    category: 'minimal',
    description: 'Single compact line for internal comms',
    variant: 'minimal',
    accentSwatch: '#222222',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 13,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#222222',
      titleColor: '#888888',
      textColor: '#aaaaaa',
      linkColor: '#888888',
      dividerStyle: 'none',
      spacing: 4,
      layoutTemplate: 'inline',
    },
  },
  {
    id: 'min-subtle',
    name: 'Whisper Grey',
    category: 'minimal',
    description: 'Stacked soft grey for minimal visual footprint',
    variant: 'full',
    accentSwatch: '#94A3B8',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 13,
      titleFontSize: 11,
      textFontSize: 11,
      nameColor: '#475569',
      titleColor: '#94A3B8',
      textColor: '#CBD5E1',
      linkColor: '#94A3B8',
      dividerStyle: 'solid',
      dividerColor: '#E2E8F0',
      dividerWidth: 1,
      spacing: 6,
      layoutTemplate: 'stacked',
    },
  },
  {
    id: 'min-reply-branded',
    name: 'Branded Reply',
    category: 'minimal',
    description: 'Banner-top compact reply with brand accent',
    variant: 'full',
    accentSwatch: DEFAULT_ACCENT,
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 15,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#777777',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'solid',
      dividerColor: DEFAULT_ACCENT,
      dividerWidth: 3,
      spacing: 8,
      layoutTemplate: 'banner-top',
    },
    includeSocialPlaceholders: true,
  },

  // ═══════════════════════════════
  // ── CORPORATE (5) ──
  // ═══════════════════════════════
  {
    id: 'corp-enterprise',
    name: 'Enterprise Blue',
    category: 'corporate',
    description: 'Two-column formal layout for multinationals',
    variant: 'full',
    accentSwatch: '#2E86AB',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1B2838',
      titleColor: '#2E86AB',
      textColor: '#4A5568',
      linkColor: '#2E86AB',
      dividerStyle: 'solid',
      dividerColor: '#2E86AB',
      dividerWidth: 2,
      spacing: 15,
      layout: 'horizontal',
      layoutTemplate: 'two-column',
    },
    includeConfidentiality: true,
  },
  {
    id: 'corp-formal',
    name: 'Boardroom',
    category: 'corporate',
    description: 'Classic serif with double divider for formal comms',
    variant: 'full',
    accentSwatch: '#1C1C1C',
    style: {
      fontFamily: "'Times New Roman', serif",
      nameFontSize: 18,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: '#1C1C1C',
      titleColor: '#4A4A4A',
      textColor: '#666666',
      linkColor: '#1C1C1C',
      dividerStyle: 'double',
      dividerColor: '#1C1C1C',
      dividerWidth: 3,
      spacing: 16,
      layout: 'horizontal',
      layoutTemplate: 'classic',
    },
    includeConfidentiality: true,
  },
  {
    id: 'corp-branded',
    name: 'Brand Forward',
    category: 'corporate',
    description: 'Card-style with prominent brand accent header',
    variant: 'full',
    accentSwatch: DEFAULT_ACCENT,
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 18,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#555555',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'solid',
      dividerColor: DEFAULT_ACCENT,
      dividerWidth: 3,
      spacing: 15,
      layout: 'horizontal',
      layoutTemplate: 'card',
    },
    includeConfidentiality: true,
    includeSocialPlaceholders: true,
  },
  {
    id: 'corp-vertical',
    name: 'Tower Layout',
    category: 'corporate',
    description: 'Stacked logo-on-top for square logos',
    variant: 'full',
    accentSwatch: '#0369A1',
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#0C4A6E',
      titleColor: '#0369A1',
      textColor: '#64748B',
      linkColor: '#0369A1',
      dividerStyle: 'solid',
      dividerColor: '#0369A1',
      dividerWidth: 2,
      spacing: 14,
      layout: 'vertical',
      layoutTemplate: 'stacked',
    },
    includeConfidentiality: true,
  },
  {
    id: 'corp-charcoal',
    name: 'Charcoal Suite',
    category: 'corporate',
    description: 'Side-banner dark palette for finance & private equity',
    variant: 'full',
    accentSwatch: '#374151',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#111827',
      titleColor: '#374151',
      textColor: '#6B7280',
      linkColor: '#374151',
      dividerStyle: 'solid',
      dividerColor: '#374151',
      dividerWidth: 1,
      spacing: 16,
      layout: 'horizontal',
      layoutTemplate: 'side-banner',
    },
    includeConfidentiality: true,
    includeSocialPlaceholders: true,
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'transperfect', label: 'TransPerfect' },
  { id: 'professional', label: 'Professional' },
  { id: 'modern', label: 'Modern' },
  { id: 'creative', label: 'Creative' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'corporate', label: 'Corporate' },
] as const;
