import { SignatureStyle } from '@/types/brand';
import { DEFAULT_DARK, DEFAULT_ACCENT, DEFAULT_CONFIDENTIALITY } from './signatureConstants';

export interface SignatureTemplate {
  id: string;
  name: string;
  category: 'professional' | 'modern' | 'creative' | 'minimal' | 'corporate';
  description: string;
  variant: 'full' | 'reply' | 'minimal';
  style: SignatureStyle;
  includeConfidentiality?: boolean;
  includeSocialPlaceholders?: boolean;
}

export const SIGNATURE_TEMPLATES: SignatureTemplate[] = [
  // ── Professional ──
  {
    id: 'pro-classic',
    name: 'Classic Professional',
    category: 'professional',
    description: 'Traditional business signature with clean divider and logo',
    variant: 'full',
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 18,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#666666',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'solid',
      dividerColor: DEFAULT_ACCENT,
      dividerWidth: 2,
      spacing: 15,
      layout: 'horizontal',
    },
    includeConfidentiality: true,
  },
  {
    id: 'pro-executive',
    name: 'Executive',
    category: 'professional',
    description: 'Premium executive style with bold typography',
    variant: 'full',
    style: {
      fontFamily: 'Georgia, serif',
      nameFontSize: 20,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1a1a1a',
      titleColor: '#8B6914',
      textColor: '#555555',
      linkColor: '#8B6914',
      dividerStyle: 'double',
      dividerColor: '#8B6914',
      dividerWidth: 3,
      spacing: 18,
      layout: 'horizontal',
    },
    includeConfidentiality: true,
  },
  {
    id: 'pro-consultant',
    name: 'Consultant',
    category: 'professional',
    description: 'Refined look for consulting and advisory roles',
    variant: 'full',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#2C3E50',
      titleColor: '#3498DB',
      textColor: '#7F8C8D',
      linkColor: '#3498DB',
      dividerStyle: 'solid',
      dividerColor: '#3498DB',
      dividerWidth: 1,
      spacing: 14,
      layout: 'horizontal',
    },
    includeConfidentiality: false,
  },

  // ── Modern ──
  {
    id: 'mod-clean',
    name: 'Modern Clean',
    category: 'modern',
    description: 'Sleek and minimal with accent color pops',
    variant: 'full',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 16,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#111111',
      titleColor: '#FF6B35',
      textColor: '#888888',
      linkColor: '#FF6B35',
      dividerStyle: 'solid',
      dividerColor: '#FF6B35',
      dividerWidth: 3,
      spacing: 12,
      layout: 'horizontal',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'mod-gradient',
    name: 'Gradient Accent',
    category: 'modern',
    description: 'Contemporary design with vibrant accent colors',
    variant: 'full',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#6C3483',
      titleColor: '#2980B9',
      textColor: '#666666',
      linkColor: '#2980B9',
      dividerStyle: 'solid',
      dividerColor: '#6C3483',
      dividerWidth: 3,
      spacing: 15,
      layout: 'horizontal',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'mod-tech',
    name: 'Tech Startup',
    category: 'modern',
    description: 'Silicon Valley style with monospace accents',
    variant: 'full',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 16,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#0D1117',
      titleColor: '#58A6FF',
      textColor: '#8B949E',
      linkColor: '#58A6FF',
      dividerStyle: 'dashed',
      dividerColor: '#30363D',
      dividerWidth: 1,
      spacing: 12,
      layout: 'horizontal',
    },
    includeSocialPlaceholders: true,
  },

  // ── Creative ──
  {
    id: 'cre-bold',
    name: 'Bold Creative',
    category: 'creative',
    description: 'High-impact design with strong color contrast',
    variant: 'full',
    style: {
      fontFamily: 'Verdana, sans-serif',
      nameFontSize: 20,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: '#E74C3C',
      titleColor: '#2C3E50',
      textColor: '#555555',
      linkColor: '#E74C3C',
      dividerStyle: 'solid',
      dividerColor: '#E74C3C',
      dividerWidth: 4,
      spacing: 16,
      layout: 'horizontal',
    },
    includeSocialPlaceholders: true,
  },
  {
    id: 'cre-artistic',
    name: 'Artistic',
    category: 'creative',
    description: 'Elegant with serif typography and fine details',
    variant: 'full',
    style: {
      fontFamily: 'Georgia, serif',
      nameFontSize: 19,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1B4332',
      titleColor: '#40916C',
      textColor: '#6B705C',
      linkColor: '#40916C',
      dividerStyle: 'dotted',
      dividerColor: '#40916C',
      dividerWidth: 2,
      spacing: 16,
      layout: 'vertical',
    },
  },
  {
    id: 'cre-neon',
    name: 'Neon Pop',
    category: 'creative',
    description: 'Energetic and eye-catching with vivid colors',
    variant: 'full',
    style: {
      fontFamily: 'Tahoma, sans-serif',
      nameFontSize: 18,
      titleFontSize: 13,
      textFontSize: 11,
      nameColor: '#7209B7',
      titleColor: '#F72585',
      textColor: '#555555',
      linkColor: '#F72585',
      dividerStyle: 'solid',
      dividerColor: '#7209B7',
      dividerWidth: 3,
      spacing: 14,
      layout: 'horizontal',
    },
    includeSocialPlaceholders: true,
  },

  // ── Minimal ──
  {
    id: 'min-simple',
    name: 'Simple Text',
    category: 'minimal',
    description: 'Clean text-only signature, no graphics',
    variant: 'minimal',
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 14,
      titleFontSize: 12,
      textFontSize: 12,
      nameColor: '#333333',
      titleColor: '#666666',
      textColor: '#999999',
      linkColor: '#666666',
      dividerStyle: 'none',
      spacing: 8,
    },
  },
  {
    id: 'min-reply',
    name: 'Compact Reply',
    category: 'minimal',
    description: 'Condensed signature for email replies',
    variant: 'reply',
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 14,
      titleFontSize: 12,
      textFontSize: 12,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#666666',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'none',
      spacing: 10,
    },
  },
  {
    id: 'min-oneline',
    name: 'One-Liner',
    category: 'minimal',
    description: 'Ultra-compact single-line signature',
    variant: 'minimal',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      nameFontSize: 13,
      titleFontSize: 12,
      textFontSize: 11,
      nameColor: '#222222',
      titleColor: '#888888',
      textColor: '#aaaaaa',
      linkColor: '#888888',
      dividerStyle: 'none',
      spacing: 4,
    },
  },

  // ── Corporate ──
  {
    id: 'corp-enterprise',
    name: 'Enterprise',
    category: 'corporate',
    description: 'Formal corporate identity with structured layout',
    variant: 'full',
    style: {
      fontFamily: "'Segoe UI', sans-serif",
      nameFontSize: 17,
      titleFontSize: 13,
      textFontSize: 12,
      nameColor: '#1B2838',
      titleColor: '#2E86AB',
      textColor: '#4A5568',
      linkColor: '#2E86AB',
      dividerStyle: 'solid',
      dividerColor: '#2E86AB',
      dividerWidth: 2,
      spacing: 15,
      layout: 'horizontal',
    },
    includeConfidentiality: true,
  },
  {
    id: 'corp-formal',
    name: 'Formal',
    category: 'corporate',
    description: 'Traditional corporate format with double divider',
    variant: 'full',
    style: {
      fontFamily: "'Times New Roman', serif",
      nameFontSize: 18,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: '#1C1C1C',
      titleColor: '#4A4A4A',
      textColor: '#666666',
      linkColor: '#1C1C1C',
      dividerStyle: 'double',
      dividerColor: '#1C1C1C',
      dividerWidth: 3,
      spacing: 16,
      layout: 'horizontal',
    },
    includeConfidentiality: true,
  },
  {
    id: 'corp-branded',
    name: 'Brand Forward',
    category: 'corporate',
    description: 'Uses your brand accent color prominently throughout',
    variant: 'full',
    style: {
      fontFamily: 'Arial, sans-serif',
      nameFontSize: 18,
      titleFontSize: 14,
      textFontSize: 12,
      nameColor: DEFAULT_DARK,
      titleColor: DEFAULT_ACCENT,
      textColor: '#555555',
      linkColor: DEFAULT_ACCENT,
      dividerStyle: 'solid',
      dividerColor: DEFAULT_ACCENT,
      dividerWidth: 3,
      spacing: 15,
      layout: 'horizontal',
    },
    includeConfidentiality: true,
    includeSocialPlaceholders: true,
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'professional', label: 'Professional' },
  { id: 'modern', label: 'Modern' },
  { id: 'creative', label: 'Creative' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'corporate', label: 'Corporate' },
] as const;
