DO $$
DECLARE
  v_brand_id uuid := '0d6d5a5f-0dd0-4e62-9ac2-285a4095de84';
  v_base     text := 'https://nhxaijbyqfkkhhoornzy.supabase.co/storage/v1/object/public/organization-assets/ec180296-dfe8-4345-869e-66b524e0a12c/brands/0d6d5a5f-0dd0-4e62-9ac2-285a4095de84/image-assets';
  v_now      text := to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"');
  v_new      jsonb;
BEGIN
  v_new := jsonb_build_array(
    jsonb_build_object('id','asset-grid-foundation-3x3','name','Grid Background — Foundation Orbs (3×3)','url',v_base||'/grid-foundation-3x3.png','size','918 KB','type','image/png','uploadedAt',v_now,'category','Grid Layout','tags',jsonb_build_array('grid','background','foundation'),'description','Symmetrical 3×3 grid of glowing Foundation orbs on deep navy — for backgrounds and section dividers.'),
    jsonb_build_object('id','asset-grid-collaborate-2x4','name','Grid Background — Collaborate Pairs (2×4)','url',v_base||'/grid-collaborate-2x4.png','size','863 KB','type','image/png','uploadedAt',v_now,'category','Grid Layout','tags',jsonb_build_array('grid','background','collaborate'),'description','Eight pairs of intersecting orbs arranged in a tight 2×4 grid — collaborative motif for backgrounds.'),
    jsonb_build_object('id','asset-grid-transform-streaks-4col','name','Grid Background — Transform Streaks (4 cols)','url',v_base||'/grid-transform-streaks-4col.png','size','958 KB','type','image/png','uploadedAt',v_now,'category','Grid Layout','tags',jsonb_build_array('grid','background','transform'),'description','Parallel streak columns on dark navy — energetic background pattern.'),
    jsonb_build_object('id','asset-rot-foundation-orb-tl','name','Rule of Thirds — Orb Top-Left','url',v_base||'/rot-foundation-orb-tl.png','size','687 KB','type','image/png','uploadedAt',v_now,'category','Rule of Thirds','tags',jsonb_build_array('rule-of-thirds','foundation','hero'),'description','Single Foundation orb anchored at the top-left third intersection — generous negative space for headlines.'),
    jsonb_build_object('id','asset-rot-collaborate-br','name','Rule of Thirds — Collaborate Bottom-Right','url',v_base||'/rot-collaborate-br.png','size','729 KB','type','image/png','uploadedAt',v_now,'category','Rule of Thirds','tags',jsonb_build_array('rule-of-thirds','collaborate','hero'),'description','Intersecting orbs anchored at bottom-right third — leaves top-left clear for editorial copy.'),
    jsonb_build_object('id','asset-rot-transform-streaks-right','name','Rule of Thirds — Diagonal Streaks Right','url',v_base||'/rot-transform-streaks-right.png','size','862 KB','type','image/png','uploadedAt',v_now,'category','Rule of Thirds','tags',jsonb_build_array('rule-of-thirds','transform','hero'),'description','Diagonal streaks emerging from the right third — directional energy with calm left negative space.'),
    jsonb_build_object('id','asset-blur-foundation-soft','name','Blur Gradient — Foundation Glow','url',v_base||'/blur-foundation-soft.png','size','795 KB','type','image/png','uploadedAt',v_now,'category','Blur Gradient','tags',jsonb_build_array('blur','gradient','foundation','background'),'description','Heavy gaussian-blurred Foundation orb melting into a navy-to-cyan gradient — abstract background.'),
    jsonb_build_object('id','asset-blur-collaborate-bokeh','name','Blur Gradient — Collaborate Bokeh','url',v_base||'/blur-collaborate-bokeh.png','size','748 KB','type','image/png','uploadedAt',v_now,'category','Blur Gradient','tags',jsonb_build_array('blur','gradient','collaborate','background'),'description','Out-of-focus pair of orbs as bokeh light spheres on a navy gradient.'),
    jsonb_build_object('id','asset-blur-transform-motion','name','Blur Gradient — Transform Motion','url',v_base||'/blur-transform-motion.png','size','1035 KB','type','image/png','uploadedAt',v_now,'category','Blur Gradient','tags',jsonb_build_array('blur','gradient','transform','motion','background'),'description','Motion-blurred light streaks dissolving into a navy-to-blue gradient — kinetic backdrop.'),
    jsonb_build_object('id','asset-zoom-foundation-orb-macro','name','Macro Zoom — Foundation Orb Surface','url',v_base||'/zoom-foundation-orb-macro.png','size','716 KB','type','image/png','uploadedAt',v_now,'category','Zoom / Detail','tags',jsonb_build_array('zoom','macro','foundation'),'description','Extreme close-up of a single Foundation orb — surface texture and luminous halo detail.'),
    jsonb_build_object('id','asset-zoom-collaborate-overlap','name','Macro Zoom — Collaborate Intersection','url',v_base||'/zoom-collaborate-overlap.png','size','742 KB','type','image/png','uploadedAt',v_now,'category','Zoom / Detail','tags',jsonb_build_array('zoom','macro','collaborate'),'description','Tight zoom on the bright overlap zone of two intersecting orbs — symbolizes shared energy.'),
    jsonb_build_object('id','asset-zoom-transform-streak-detail','name','Macro Zoom — Streak Detail','url',v_base||'/zoom-transform-streak-detail.png','size','918 KB','type','image/png','uploadedAt',v_now,'category','Zoom / Detail','tags',jsonb_build_array('zoom','macro','transform'),'description','Extreme close-up of a single light streak — speed and luminosity captured up close.'),
    jsonb_build_object('id','asset-center-foundation-spotlight','name','Centered Hero — Foundation Spotlight','url',v_base||'/center-foundation-spotlight.png','size','743 KB','type','image/png','uploadedAt',v_now,'category','Centered Hero','tags',jsonb_build_array('centered','hero','foundation'),'description','Single Foundation orb dead-center with vignette — clean centered hero composition.'),
    jsonb_build_object('id','asset-center-collaborate-symmetric','name','Centered Hero — Collaborate Symmetry','url',v_base||'/center-collaborate-symmetric.png','size','770 KB','type','image/png','uploadedAt',v_now,'category','Centered Hero','tags',jsonb_build_array('centered','hero','collaborate'),'description','Symmetric pair of intersecting orbs centered horizontally — partnership hero shot.'),
    jsonb_build_object('id','asset-portrait-transform-vertical-flow','name','Portrait — Vertical Streak Flow','url',v_base||'/portrait-transform-vertical-flow.png','size','958 KB','type','image/png','uploadedAt',v_now,'category','Portrait','tags',jsonb_build_array('portrait','vertical','transform'),'description','Vertical streaks rising from bottom to top — portrait hero for mobile and side panels.'),
    jsonb_build_object('id','asset-portrait-foundation-stack','name','Portrait — Stacked Orbs','url',v_base||'/portrait-foundation-stack.png','size','797 KB','type','image/png','uploadedAt',v_now,'category','Portrait','tags',jsonb_build_array('portrait','vertical','foundation'),'description','Three Foundation orbs stacked vertically with rhythmic spacing — portrait poster.'),
    jsonb_build_object('id','asset-banner-collaborate-trio','name','Wide Banner — Collaborate Trio','url',v_base||'/banner-collaborate-trio.png','size','770 KB','type','image/png','uploadedAt',v_now,'category','Wide Banner','tags',jsonb_build_array('banner','wide','collaborate'),'description','Three pairs of intersecting orbs spanning a wide banner — for hero strips and section headers.'),
    jsonb_build_object('id','asset-banner-transform-horizon','name','Wide Banner — Transform Horizon','url',v_base||'/banner-transform-horizon.png','size','854 KB','type','image/png','uploadedAt',v_now,'category','Wide Banner','tags',jsonb_build_array('banner','wide','transform','horizon'),'description','Long horizontal horizon of streaks — ultra-wide banner suggesting forward momentum.')
  );

  UPDATE public.brands
  SET guide_data = jsonb_set(
    COALESCE(guide_data, '{}'::jsonb),
    '{imageAssets}',
    COALESCE(guide_data->'imageAssets', '[]'::jsonb) || v_new
  ),
  updated_at = now()
  WHERE id = v_brand_id;
END $$;